### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(UI/LeandrocxUIDesignContent)
add_subdirectory(UI/LeandrocxUIDesign)
add_subdirectory(App)
add_subdirectory(UI/Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    LeandrocxUIDesignContentplugin
    LeandrocxUIDesignplugin)
